// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeSiiQ1w7de3tT9ND3wc177nwufNIDKbI',
    appId: '1:797036482839:web:6d28a549b6a94ff09da752',
    messagingSenderId: '797036482839',
    projectId: 'farmo-404ba',
    authDomain: 'farmo-404ba.firebaseapp.com',
    storageBucket: 'farmo-404ba.appspot.com',
    measurementId: 'G-M7CXNXDRF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTzaQZknu2dKpYvvfULKzlveduZmM7jTM',
    appId: '1:797036482839:android:607ed5829973af589da752',
    messagingSenderId: '797036482839',
    projectId: 'farmo-404ba',
    storageBucket: 'farmo-404ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi4fjcqzoCjd7VJkuTkkTWKztdF67Ga7o',
    appId: '1:797036482839:ios:112ac11258f4e8f39da752',
    messagingSenderId: '797036482839',
    projectId: 'farmo-404ba',
    storageBucket: 'farmo-404ba.appspot.com',
    iosBundleId: 'com.syntheticdevs.farmo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi4fjcqzoCjd7VJkuTkkTWKztdF67Ga7o',
    appId: '1:797036482839:ios:1d5d33080f97afc49da752',
    messagingSenderId: '797036482839',
    projectId: 'farmo-404ba',
    storageBucket: 'farmo-404ba.appspot.com',
    iosBundleId: 'com.syntheticdevs.farmo.RunnerTests',
  );
}
